# Generated by Django 4.2.17 on 2024-12-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='HousingArea',
            field=models.TextField(choices=[('bedroom', 'Bedroom'), ('bathroom', 'Bathroom'), ('living room', 'Living Room'), ('kitchen', 'Kitchen'), ('laundry room', 'Laundry Room'), ('garage', 'Garage'), ('yard', 'Yard')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
