# Generated by Django 4.2.17 on 2024-12-09 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_time', models.DateTimeField(null=True)),
                ('description', models.TextField(max_length=1024)),
                ('address', models.TextField(max_length=1024)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Community Events',
            },
        ),
    ]
