# Generated by Django 4.2.17 on 2024-12-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
