# Generated by Django 4.2.17 on 2024-12-11 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=1024)),
                ('logo', models.ImageField(upload_to='images/')),
                ('description', models.TextField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='communityaddresses',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.community'),
        ),
    ]
