# Generated by Django 4.2.17 on 2024-12-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_community_communityaddresses_community'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': 'Community', 'verbose_name_plural': 'Community'},
        ),
        migrations.AlterField(
            model_name='member',
            name='firstName',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastName',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
