# Generated by Django 4.2.17 on 2024-12-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_community_options_alter_member_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='district_map',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
