# Generated by Django 4.2.17 on 2024-12-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_community_district_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
