# Generated by Django 4.2.17 on 2024-12-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
